---
Applikation: "mypals"
Namespace: "a-lot-of-pals"

#Specify Loadbalancer IP
LoadBalancerIP: 10.100.1.100

#only one release per namespace can manage the builressources, so this is only allowed to be `true` once per namespace
createBuildResources: true

#currently only nfs storage backend with a fixed ip adress and storagepath is supported
StorageServerIP: 10.100.1.2

env:
  SERVER_NAME: YourServerNameHere
  SERVER_DESCRIPTION: None
  ADMIN_PASSWORD: adminPasswordHere
  SERVER_PASSWORD: serverPasswordHere
  TZ: Europe/Berlin
  KUBERNETES: true
  ACTIVE_UNKO: false
  ALWAYS_UPDATE_ON_START: true
  AUTO_RESET_GUILD_NO_ONLINE_PLAYERS: false
  AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS: 72.000000
  BACKUP_CRON_EXPRESSION: 0 * * * *
  BACKUP_ENABLED: true
  BACKUP_RETENTION_AMOUNT_TO_KEEP: 30
  BACKUP_RETENTION_POLICY: false
  BAN_LIST_URL: https://api.palworldgame.com/api/banlist.txt
  BASE_CAMP_MAX_NUM: 128
  BASE_CAMP_WORKER_MAXNUM: 15
  BUILD_OBJECT_DAMAGE_RATE: 1.000000
  BUILD_OBJECT_DETERIORATION_DAMAGE_RATE: 1.000000
  CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP: false
  COOP_PLAYER_MAX_NUM: 4
  COLLECTION_DROP_RATE: 1.000000
  COLLECTION_OBJECT_HP_RATE: 1.000000
  COLLECTION_OBJECT_RESPAWN_SPEED_RATE: 1.000000
  COMMUNITY_SERVER: false
  DAYTIME_SPEEDRATE: 1.000000
  DEATH_PENALTY: All
  DIFFICULTY: None
  DROP_ITEM_ALIVE_MAX_HOURS: 1.000000
  DROP_ITEM_MAX_NUM: 3000
  DROP_ITEM_MAX_NUM_UNKO: 100
  ENABLE_AIM_ASSIST_KEYBOARD: false
  ENABLE_AIM_ASSIST_PAD: true
  ENABLE_DEFENSE_OTHER_GUILD_PLAYER: false
  ENABLE_FAST_TRAVEL: true
  ENABLE_FRIENDLY_FIRE: false
  ENABLE_INVADER_ENEMY: true
  ENABLE_NON_LOGIN_PENALTY: true
  ENABLE_PLAYER_TO_PLAYER_DAMAGE: false
  ENEMY_DROP_ITEM_RATE: 1.000000
  EXIST_PLAYER_AFTER_LOGOUT: false
  EXP_RATE: 1.000000
  GUILD_PLAYER_MAX_NUM: 20
  IS_MULTIPLAY: false
  IS_PVP: false
  IS_START_LOCATION_SELECT_BY_MAP: true
  MAX_PLAYERS: 32
  MULTITHREAD_ENABLED: true
  NETSERVERMAXTICKRATE: 120
  NIGHTTIME_SPEEDRATE: 1.000000
  PAL_AUTO_HP_REGENE_RATE: 1.000000
  PAL_AUTO_HP_REGENE_RATE_IN_SLEEP: 1.000000
  PAL_CAPTURE_RATE: 1.000000
  PAL_DAMAGE_RATE_ATTACK: 1.000000
  PAL_DAMAGE_RATE_DEFENSE: 1.000000
  PAL_EGG_DEFAULT_HATCHING_TIME: 3.000000
  PAL_SPAWN_NUM_RATE: 1.000000
  PAL_STAMINA_DECREACE_RATE: 1.000000
  PAL_STOMACH_DECREACE_RATE: 1.000000
  PLAYER_AUTO_HP_REGENE_RATE: 1.000000
  PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP: 1.000000
  PLAYER_DAMAGE_RATE_ATTACK: 1.000000
  PLAYER_DAMAGE_RATE_DEFENSE: 1.000000
  PLAYER_STAMINA_DECREACE_RATE: 1.000000
  PLAYER_STOMACH_DECREASE_RATE: 1.000000
  PUBLIC_IP: 
  PUBLIC_PORT: 8211
  RCON_ENABLED: true
  RCON_PLAYER_DETECTION: true
  RCON_PLAYER_DETECTION_CHECK_INTERVAL: 15
  RCON_PLAYER_DETECTION_STARTUP_DELAY: 60
  RCON_PORT: 25575
  REGION: "EU"
  RESTART_ENABLED: false
  RESTART_DEBUG_OVERRIDE: false
  RESTART_CRON_EXPRESSION: "0 18 * * *"
  SERVER_SETTINGS_MODE: auto
  STEAMCMD_VALIDATE_FILES: true
  USEAUTH: true
  WEBHOOK_ENABLED: false
  WEBHOOK_CONTENT_TITLE: "Status update"
  WEBHOOK_INFO_COLOR: "2849520"
  WEBHOOK_INFO_DESCRIPTION: "This is an info from the server"
  WEBHOOK_INFO_TITLE: "Info"
  WEBHOOK_INSTALL_TITLE: "Installing server"
  WEBHOOK_INSTALL_DESCRIPTION: "Server is being installed"
  WEBHOOK_INSTALL_COLOR: "2849520"
  WEBHOOK_RESTART_TITLE: "Server is restarting soon"
  WEBHOOK_RESTART_DESCRIPTION: "The gameserver is restarting in 15 minutes"
  WEBHOOK_RESTART_COLOR: "15593515"
  WEBHOOK_START_COLOR: "2328576"
  WEBHOOK_START_DESCRIPTION: "The gameserver is starting"
  WEBHOOK_START_TITLE: "Server is starting"
  WEBHOOK_STOP_COLOR: "7413016"
  WEBHOOK_STOP_DESCRIPTION: "The gameserver has been stopped"
  WEBHOOK_STOP_TITLE: "Server has been stopped"
  WEBHOOK_URL: "YOUR-URL-IN-HERE"
  WORK_SPEED_RATE: 1.000000
