{{ if .Values.createBuildResources }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: palworld-ocp
  namespace: {{ .Values.Namespace }}
  labels:
    build: palworld-ocp
    app.kubernetes.io/name: {{ .Values.Applikation }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'palworld-ocp:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'steamcmd:ocp'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/Cardes/docker-palworld-dedicated-server.git'
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        lastTriggeredImageID: 'steamcmd:ocp'
    - type: Generic
      generic:
        secretReference:
          name: {{ .Values.Applikation }}-webhooksecret
  runPolicy: Serial
{{ end }}