---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.Applikation }}-env
  namespace: {{ .Values.Namespace }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: "{{ $value }}"
{{- end }}
