{{ if .Values.createBuildResources }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: debian
  namespace: {{ .Values.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.Applikation }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: bookworm-slim
      annotations: null
      from:
        kind: DockerImage
        name: 'docker.io/debian:bookworm-slim'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
{{ end }}