{{ if .Values.createBuildResources }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: steamcmd
  namespace: {{ .Values.Namespace }}
  labels:
    build: steamcmd-ocp
    app.kubernetes.io/name: {{ .Values.Applikation }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  lookupPolicy:
    local: false
{{ end }}