---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Applikation }}-data
  labels:
    app.kubernetes.io/name: {{ .Values.Applikation }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=4.1
  claimRef:
    name: {{ .Values.Applikation }}-data
    kind: persistentVolumeClaim
    namespace: {{ .Values.Namespace }}
  storageClassName: manual
  nfs:
    path: /kubes/manual-{{ .Values.Namespace }}-{{ .Values.Applikation }}-data
    server: {{ .Values.StorageServerIP }}