---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.Applikation }}-data
  namespace: {{ .Values.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  volumeName: {{ .Values.Applikation }}-data
